lab-2
MairianeT/VolZenit-Web pull request #7
Opened 2022-10-02 20:46 UTC by MairianeT

2022-10-10 12:28 UTC, BakasaRus requested changes
Не хватает `letter-spacing`

2022-10-10 12:28 UTC, BakasaRus commented on style.css
> +    font-family: sans-serif;
Нужно будет подключить шрифт через Google Fonts

2022-10-10 12:28 UTC, BakasaRus commented on style.css
> +    color: #1c3e7d;
Как работает указание цвета в этой форме?

2022-10-10 15:37 UTC, MairianeT commented on style.css
> +    color: #1c3e7d;
Формат HEX: шестнадцатеричное представление RGB. Три группы шестнадцатеричных цифр, где каждая группа отвечает за свой цвет.

2022-10-17 11:20 UTC, BakasaRus approved these changes

2022-10-17 11:50 UTC, merged